env:
  - CGO_ENABLED=0

builds:
  - id: default
    main: ./cmd/heimdall/
    flags:
      - -buildvcs
      - -trimpath
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64

archives:
  - id: default
    format: binary
    name_template: >-
      {{- .Binary }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{- .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
