name: Release

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      VERSION: "${{ github.ref_name }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Test
        run: make test
      - name: Build
        run: |
          name="${{ github.repository }}"
          name="${name##*/}"
          for os_arch in darwin/arm64 linux/amd64 windows/amd64; do
            echo "::group::Building ${os_arch}"
            export GOOS="${os_arch%/*}" GOARCH="${os_arch#*/}"
            dist="${os_arch//\//_}"
            dist="${dist/darwin/macOS}"
            dist="${dist/amd64/x86_64}"

            builddir="dist/${dist}" make build
            mv "dist/${dist}/"* "dist/${dist}/${name}_${VERSION}_${dist}$(go env GOEXE)"
            echo "::endgroup::"
          done
      - name: Release
        run: |
          gh release upload "${{ github.ref_name }}" dist/*_*/*_${VERSION}_* --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
